import { TypographySystemOptions } from "@mui/joy/styles/types";

declare module "@mui/joy/styles" {
  interface TypographySystemOverrides {
    "display-2xl.regular": true;
    "display-2xl.medium": true;
    "display-2xl.semibold": true;
    "display-2xl.bold": true;
    "display-xl.regular": true;
    "display-xl.medium": true;
    "display-xl.semibold": true;
    "display-xl.bold": true;
    "display-lg.regular": true;
    "display-lg.medium": true;
    "display-lg.semibold": true;
    "display-lg.bold": true;
    "display-md.regular": true;
    "display-md.medium": true;
    "display-md.semibold": true;
    "display-md.bold": true;
    "display-sm.regular": true;
    "display-sm.medium": true;
    "display-sm.semibold": true;
    "display-sm.bold": true;
    "display-xs.regular": true;
    "display-xs.medium": true;
    "display-xs.semibold": true;
    "display-xs.bold": true;
    "text-lg.regular": true;
    "text-lg.medium": true;
    "text-lg.semibold": true;
    "text-lg.bold": true;
    "text-md.regular": true;
    "text-md.medium": true;
    "text-md.semibold": true;
    "text-md.bold": true;
    "text-sm.regular": true;
    "text-sm.medium": true;
    "text-sm.semibold": true;
    "text-sm.bold": true;
    "text-xs.regular": true;
    "text-xs.medium": true;
    "text-xs.semibold": true;
    "text-xs.bold": true;
  }
}

export const typography: Partial<TypographySystemOptions> = {
  "display-2xl.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-0)",
    fontSize: "var(--joy-fontSize-10)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-10)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-2xl.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-0)",
    fontSize: "var(--joy-fontSize-10)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-10)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-2xl.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-0)",
    fontSize: "var(--joy-fontSize-10)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-10)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-2xl.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-0)",
    fontSize: "var(--joy-fontSize-10)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-10)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xl.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-1)",
    fontSize: "var(--joy-fontSize-9)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-9)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xl.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-1)",
    fontSize: "var(--joy-fontSize-9)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-9)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xl.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-1)",
    fontSize: "var(--joy-fontSize-9)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-9)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xl.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-1)",
    fontSize: "var(--joy-fontSize-9)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-9)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-lg.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-2)",
    fontSize: "var(--joy-fontSize-8)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-8)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-lg.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-2)",
    fontSize: "var(--joy-fontSize-8)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-8)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-lg.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-2)",
    fontSize: "var(--joy-fontSize-8)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-8)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-lg.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-2)",
    fontSize: "var(--joy-fontSize-8)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-8)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-md.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-3)",
    fontSize: "var(--joy-fontSize-7)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-7)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-md.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-3)",
    fontSize: "var(--joy-fontSize-7)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-7)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-md.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-3)",
    fontSize: "var(--joy-fontSize-7)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-7)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-md.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-3)",
    fontSize: "var(--joy-fontSize-7)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-7)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-sm.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-4)",
    fontSize: "var(--joy-fontSize-6)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-6)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-sm.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-4)",
    fontSize: "var(--joy-fontSize-6)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-6)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-sm.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-4)",
    fontSize: "var(--joy-fontSize-6)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-6)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-sm.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-4)",
    fontSize: "var(--joy-fontSize-6)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-6)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xs.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-5)",
    fontSize: "var(--joy-fontSize-5)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-5)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xs.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-5)",
    fontSize: "var(--joy-fontSize-5)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-5)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xs.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-5)",
    fontSize: "var(--joy-fontSize-5)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-5)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "display-xs.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-5)",
    fontSize: "var(--joy-fontSize-5)",
    letterSpacing: "var(--joy-letterSpacing-0)",
    paragraphSpacing: "var(--joy-paragraphSpacing-5)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-lg.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-7)",
    fontSize: "var(--joy-fontSize-3)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-3)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-lg.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-7)",
    fontSize: "var(--joy-fontSize-3)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-3)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-lg.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-7)",
    fontSize: "var(--joy-fontSize-3)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-3)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-lg.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-7)",
    fontSize: "var(--joy-fontSize-3)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-3)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-md.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-8)",
    fontSize: "var(--joy-fontSize-2)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-2)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-md.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-8)",
    fontSize: "var(--joy-fontSize-2)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-2)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-md.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-8)",
    fontSize: "var(--joy-fontSize-2)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-2)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-md.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-8)",
    fontSize: "var(--joy-fontSize-2)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-2)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-sm.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-9)",
    fontSize: "var(--joy-fontSize-1)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-1)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-sm.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-9)",
    fontSize: "var(--joy-fontSize-1)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-1)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-sm.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-9)",
    fontSize: "var(--joy-fontSize-1)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-1)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-sm.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-9)",
    fontSize: "var(--joy-fontSize-1)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-1)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-xs.regular": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-0)",
    lineHeight: "var(--joy-lineHeight-10)",
    fontSize: "var(--joy-fontSize-0)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-0)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-xs.medium": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-1)",
    lineHeight: "var(--joy-lineHeight-10)",
    fontSize: "var(--joy-fontSize-0)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-0)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-xs.semibold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-2)",
    lineHeight: "var(--joy-lineHeight-10)",
    fontSize: "var(--joy-fontSize-0)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-0)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
  "text-xs.bold": {
    fontFamily: "var(--joy-fontFamily-inter)",
    fontWeight: "var(--joy-fontWeight-inter-3)",
    lineHeight: "var(--joy-lineHeight-10)",
    fontSize: "var(--joy-fontSize-0)",
    letterSpacing: "var(--joy-letterSpacing-1)",
    paragraphSpacing: "var(--joy-paragraphSpacing-0)",
    paragraphIndent: "var(--joy-paragraphIndent-0)",
    textCase: "var(--joy-textCase-none)",
    textDecoration: "var(--joy-textDecoration-none)",
  },
};
